### ISSUE TITLE
State resources should not be TF controlled

### ISSUE THREAD

**Issue by bryantbiggs** [rust-lang/simpleinfra#20]
The S3 bucket and DynamoDB table used to store the backend state file(s) and control locking should not be controlled in Terraform. Its a cyclical dependency and if anything happens to those resources, it could be catastrophic. 

Remove this file https://github.com/rust-lang/simpleinfra/blob/master/terraform/terraform-state.tf

Then run manually:
```bash
terraform state rm aws_s3_bucket.rust_terraform aws_dynamodb_table.terraform_state_lock
```

**Comment by pietroalbini** [comment]
Yeah, now that I think about this keeping those resources together with the rest was not a great decision, thanks for pointing it out!

There is one problem with stopping to manage those resources with Terraform: our AWS account is inside an organization for billing purposes, but one of the policies of this organization is that the owners of it need to have an administrator role in our account they can assume. This policy makes sense for all the other accounts in that organization, we're just a corner case unfortunately.

The Terraform state contains sensitive data, so the team decided to restrict access to the S3 bucket only to selected members of the team, preventing any action on it by other IAM users/roles with admin access through a bucket policy.

Changing this policy manually is a *pain*, since as far as I'm aware the only way to restrict that is by doing something like this:

```json
{
  "Effect": "Deny",
  "Action": "s3:*",
  "Condition": {
    "StringNotLike": {
      "aws:userId": [
        "account_id",
        "iam_user_id_1",
        "iam_user_id_2"
      ]
    }
  }
}
```

We don't expect the Account ID to change, but in the future we may add or remove IAM users authorized to access that bucket. Unfortunately the IAM User IDs are opaque identifiers (`AAAAAAAAAAAAAAAAAAAAA`): that makes it hard to see who has access currently by looking at the policy, and it discourages adding new members as someone has to go fetch their ID.

Another approach I think could be viable is to create a separate Terraform state file just managing the S3 bucket and the DynamoDB table (as suggested by #22): this way the chances of a disaster happening on that state file are really slim (as it just contains two resources and it's rarely changed).

I prepared a quick proof of concept in https://github.com/pietroalbini/simpleinfra/commit/a03cef22dac6bf82fe3930ea76303b2ec34632f8, and I'd love to get your feedback on that.

**Comment by bryantbiggs** [comment]
If that is the use case, just for user access management, then I would still follow my advice in removing this from Terraform control and just simply use a data source for the bucket and a bucket policy resource in its place. 

```hcl
data "aws_s3_bucket" "rust_terraform" {
  bucket = "rust-terraform"
}

resource "aws_s3_bucket_policy" "rust_terraform" {
  bucket = data.aws_s3_bucket.rust_terraform.id

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::rust-terraform",
        "arn:aws:s3:::rust-terraform/*"
      ],
      "Condition": {
        "StringNotLike": {
          "aws:userId": [
            "${data.aws_caller_identity.current.account_id}",
            "${aws_iam_user.acrichto.unique_id}",
            "${aws_iam_user.aidanhs.unique_id}",
            "${aws_iam_user.pietro.unique_id}",
            "${aws_iam_user.simulacrum.unique_id}"
          ]
        }
      }
    }
  ]
}
EOF
}
```

**Comment by pietroalbini** [comment]
Good point!
