### ISSUE TITLE
Terraform state management

### ISSUE THREAD

**Issue by bryantbiggs** [rust-lang/simpleinfra#22]
It is a recommended best practice to segment your terraform state so that you can limit the blast radius in the event of adverse modifications. How it is segmented is completely subjective, but I would suggest segmenting it based on service/functionality. 

For example:
- `docs-rs`
- `crates-io`
- `rust-lang`
- `highfive`
- `global` - things like Route53 zones, general IAM settings not specific to above services, etc.

This is just a rough first pass but it demonstrates the approach. Changes to `docs-rs` will not take down or affect any other services when changes to the infrastructure are made. It also speeds up the develop/deploy process as less resources are managed under each statefile and less time is traversing the statefile to compare and report.

Reach out to me at bryantbiggs@clowd.haus and lets chat about overall infrastructure. I have been working with Terraform for over 4 years now and have built out/transformed several environments over the years and am willing to help here if there is interest.

**Comment by pietroalbini** [comment]
Yeah, this is a good point, and splitting the state file was one of the things I wanted to do next.

This setup started as a sort of exploration on how suitable Terraform was for us: we're an open source project with an infra team made mostly of volunteers, so our requirements are a bit different than traditional infrastructure (we still need to decide if and how much we want to commit to Terraform in the long term).

Unfortunately a few of the early decisions (such as having a single state file to reduce complexity) were not great, and some of the initial configuration could be rewritten in a better way, but if we commit to Terraform in some way we'll definitely spend time cleaning them up.

> Reach out to me at bryantbiggs@clowd.haus and lets chat about overall infrastructure. I have been working with Terraform for over 4 years now and have built out/transformed several environments over the years and am willing to help here if there is interest.

Having a chat would be great! I'd slightly prefer to do it [on our Discord](https://discord.gg/rust-lang) (channel `#infra`) instead of email, to allow other interested members of the team to chime in. Let me know if that's a problem for you.
