### ISSUE TITLE
Crates.io Index

### ISSUE THREAD

**Issue by bryantbiggs** [rust-lang/simpleinfra#24]
The https://github.com/rust-lang/crates.io-index should be hosted in something like DynamoDB. DynamoDB is fast for many reads/writes at the same time, auto partitions based on key structure, can be configured with caching (DAX), as well as global tables for fast lookup anywhere in the world. Plus is this is what backes crates.io and that runs in AWS, makes sense to keep it all on the AWS network/backbone and not rely on Github's SLA

**Comment by pietroalbini** [comment]
This is not really a decision the infra team can make: our role is to provide what the other teams need, not dictate what they have to use (within reason).

---

Now, with my crates.io team member hat on, I don't think using DynamoDB suits us. Yes, the crates.io webapp runs on Heroku (thus AWS behind the scenes), but the webapp itself doesn't rely on the index on GitHub. The only interaction the webapp has with the index is pushing a new commit when a change (new release, yanking) happens, and that is automatically retried if GitHub is down.

The actual consumers of the data in the index are users of Cargo downloading crates and resolving dependencies, or other applications pulling the index to fetch crates.io's data (as we recommend doing that instead of hitting the HTTP API to avoid being rate limited). This adds a few roadblocks:

* Any change to the index has to go through Rust's [RFC process](https://github.com/rust-lang/rfcs), and we need to keep backward compatibility for older clients and consumers.
* The data source must be publicly readable, as almost all of the reads are not from us.

By the way, [RFC 2789](https://github.com/rust-lang/rfcs/pull/2789) is proposing to serve a copy of that repository through HTTP, so that newer clients can query it directly. Still, if we do that I'd probably use S3+CloudFront instead of DynamoDB.

**Comment by bryantbiggs** [comment]
ah, ok now I see whats happening better - thanks for that insight. For serving, yes I completely agree that CloudFront is the best approach since it will be accessed heavily by all end users. However, if that does end up being the case, the origin for CloudFront still needs to be determined. Just plopping a large file in S3 will mean the cache is invalidated on each update so that won't work. To use just the plan ol S3 route with CloudFront, you would have to have each index in its own separate file and then the HTTP requests mapped to those files - that doesn't seem very scalable. The only route with CloudFront that I could see possibly working would be to have a set of EC2 servers behind an ALB as the origin for CloudFront - caching the individual get requests for each index. It won't be the most performant and cache consistency will be quite low.

**Comment by bryantbiggs** [comment]
Closing this here since its being discussed in the RFC you referenced

**Comment by pietroalbini** [comment]
> However, if that does end up being the case, the origin for CloudFront still needs to be determined. Just plopping a large file in S3 will mean the cache is invalidated on each update so that won't work. To use just the plan ol S3 route with CloudFront, you would have to have each index in its own separate file and then the HTTP requests mapped to those files - that doesn't seem very scalable. The only route with CloudFront that I could see possibly working would be to have a set of EC2 servers behind an ALB as the origin for CloudFront - caching the individual get requests for each index. It won't be the most performant and cache consistency will be quite low.

I havent't thought what the best approach for this will be (the RFC is not accepted yet), but I still think S3 might be the most sensible choice here.

The index is not a single file, but a file for each crate (for example [this](https://github.com/rust-lang/crates.io-index/blob/master/ru/st/rustwide)) in a directory structure, so there is not a problem of invalidating the whole index every time. Still, if/when we end up implementing this we'll need to figure out a proper invalidation strategy because crates depend on each other so the cache needs to be consistent.
