### ISSUE TITLE
Outdated (Rust 1.17.0) docs hosted on static.rust-lang.org

### ISSUE THREAD

**Issue by softmoth** [rust-lang/simpleinfra#568]
### What needs to be fixed?

Old docs, with "master" in the URL, are accessible from static.rust-lang.org. This may show up in web search results, older forum posts, etc.

### Page(s) Affected

https://static.rust-lang.org/doc/master/rust.html
https://static.rust-lang.org/doc/master/reference.html

### Suggested Improvement

Redirect to the current reference documentation:  https://doc.rust-lang.org/reference/

**Comment by MarcoIeni** [comment]
The `static-rust-lang-org` s3 bucket contains a `master` folder with these outdated files.

I suggest to:
- change the static [lambda](https://github.com/rust-lang/simpleinfra/blob/master/terragrunt/modules/release-distribution/lambdas/static-router/index.js) to implement that redirect you suggested
- remove the `master` directory from the S3 bucket.

Do you want to send a PR to implement the redirect? :)
we have a similar lambda [here](https://github.com/rust-lang/simpleinfra/blob/5a272d1d52cd099280e39584543f0dbfa26c86bc/terragrunt/modules/release-distribution/lambdas/doc-router/index.js#L3) that you can use as another example.

**Comment by MarcoIeni** [comment]
I applied the changes.

https://cloudfront-dev-static.rust-lang.org/doc/master/rust.html works!
`reference.html` is not working yet because of caching on my browser probably.

`index.js` is for cloudfront. We also need to update fastly. I forgot to mention this in the issue, sorry!

Here's the location:

https://github.com/softmoth/simpleinfra/blob/8df16d45f2b95e77081928ea9f66f53267b91e80/terragrunt/modules/release-distribution/fastly-static.tf#L97

**Comment by MarcoIeni** [comment]
Deployed to production as well 👍
